description: >
  Install node dependencies.

executor: default

steps:
  - checkout_with_workspace
  - set_node_version
  - restore_cache:
      key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}-{{ checksum ".nvmrc" }}
  # https://medium.com/@mdsky1986/caching-node-dependencies-when-using-npm-ci-89fe3f46404a
  - run:
      name: Install node dependencies
      # --legacy-peer-deps flag should be removed once https://github.com/wooserv/tawfeer-plugin/issues/1218 is resolved
      command: |
        if test -d "node_modules"; then
          echo "package.json and package-lock.json unchanged. Using cache."
        else
          npm ci --legacy-peer-deps --loglevel warn --yes
        fi
  - save_cache:
      key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}-{{ checksum ".nvmrc" }}
      paths:
        - node_modules
  - persist_to_workspace:
      root: ~/
      paths:
        - project
